import type { NextPage } from "next";
import Head from "next/head";
import axios from "axios";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Neu Vibes Music Video Discovery</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col items-center justify-center w-1/2 min-h-screen mx-auto">
        <h1 className="font-black text-center uppercase text-amber-300 text-7xl">
          Neu Vibez
        </h1>

      </div>
    </>
  );
};

export const getServerSideProps = async () => {
  const response = await axios.get("http://localhost:3000/api/post");
  console.log(response.data.name);
  return {
    props: {}
  };
};
export default Home;
